# Copyright 2022 Mattermost, Inc.
name: "mattermost/add-label"
description: "An action that adds label"

inputs:
  repository_full_name:
    description: "The full name of the repository"
    required: false
  pr_number:
    description: "The pr number for the label addition"
    required: false
  labels:
    description: "The labels to add"
    required: true

runs:
  using: composite
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      shell: bash

    - name: ci/update-commit-status
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        script: |
          try {
            var labels = core.getInput('labels', { required: true }).split('\n').filter(l => l !== '');
            core.info(`${labels}`);

            var repository_full_name = core.getInput('repository_full_name') === '' ? ${{ github.repository }} : core.getInput('repository_full_name', { required: false });
            core.info(`${repository_full_name}`);
            
            var number = core.getInput('pr_number', { required: false }) === '' ? ${{ github.event.number }} : parseInt(core.getInput('pr_number', { required: false }));
            core.info(`${number}`);

            if (labels.length === 0) {
              core.error("Labels are empty");
              return;
            }

            await github.rest.issues.addLabels({
              owner: repository_full_name.split("/")[0],
              repo: repository_full_name.split("/")[1],
              issue_number: number,
              labels
            });

            core.info("Labels added successfully");
          } catch (err) {
            core.error(`Failed to add labels: ${labels}`);
            core.setFailed(`Action failed with error: ${err}`);
          }
