# Copyright 2022 Mattermost, Inc.
name: "mattermost/add-label"
description: "An action that adds label"

inputs:
  repository_full_name:
    description: "The full name of the repository"
    required: false
  pr_number:
    description: "The pr number for the label addition"
    required: false
  labels:
    description: "The labels to add"
    required: true

runs:
  using: composite
  steps:
    - name: ci/update-commit-status
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      env:
        LABELS: ${{ inputs.labels }}
        PR_NUMBER: ${{ inputs.pr_number }}
        REPOSITORY_FULL_NAME: ${{ inputs.repository_full_name }}
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        script: |
          try {
            var { LABELS, REPOSITORY_FULL_NAME, PR_NUMBER } = process.env;

            var labels = LABELS.split("\n").filter(l => l !== '');
            core.info(`${labels}`);

            var repository_full_name = REPOSITORY_FULL_NAME === '' ? ${{ github.repository }} : REPOSITORY_FULL_NAME;
            core.info(`${repository_full_name}`);
            
            var number = PR_NUMBER === '' ? ${{ github.event.number }} : parseInt(PR_NUMBER);
            core.info(`${number}`);

            if (labels.length === 0) {
              core.error("Labels are empty");
              return;
            }

            await github.rest.issues.addLabels({
              owner: repository_full_name.split("/")[0],
              repo: repository_full_name.split("/")[1],
              issue_number: number,
              labels
            });

            core.info("Labels added successfully");
          } catch (err) {
            core.error(`Failed to add labels: ${labels}`);
            core.setFailed(`Action failed with error: ${err}`);
          }
