name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "What a nice weather"
          echo "Forked line from the forked repo"
          echo "Another Forked Line"
          echo "What a nice test"

  persist-pr-number:
    runs-on: ubuntu-22.04
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo ${PR_NUMBER} > ./pr/pr_number

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pr_number
          path: pr/
