name: test

on:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "What a nice weather"
          echo "Forked line from the forked repo"
          echo "Another Forked Line"
          echo "What a nice test"
          echo "Best test ever"

      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            var repository_full_name = "${{ github.repository }}";
            var number = parseInt("${{ github.event.number }}");

            var existingLabels = await github.rest.issues.listLabelsOnIssue({
              owner: repository_full_name.split("/")[0],
              repo: repository_full_name.split("/")[1],
              issue_number: number,
            });

            core.info(`${existingLabels}`);

  add-label:
    runs-on: ubuntu-22.04
    ## Only add label for contributors PRs
    if: github.event.pull_request.base.repo.full_name != github.event.pull_request.head.repo.full_name
    needs:
      - testing
    steps:
      - uses: mattermost/actions/delivery/add-labels@feat/label-actions
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          labels: PrivateTests
