name: test

on:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "What a nice weather"
          echo "Forked line from the forked repo"
          echo "Another Forked Line"
          echo "What a nice test"
          echo "Best test ever"
          echo "Another change"
          echo "Another change"

  persist-pr-number:
    runs-on: ubuntu-22.04
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo ${PR_NUMBER} > ./pr/pr_number

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: pr_number
          path: pr/
