name: test

on:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "What a nice weather"
          echo "Forked line from the forked repo"
          echo "Another Forked Line"
          echo "What a nice test"
