name: test

on:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "What a nice weather"
          echo "Forked line from the forked repo"
          echo "Another Forked Line"
          echo "What a nice test"
          echo "Best test ever"

  add-label:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # 3.5.2

      - uses: ./.github/actions/add-label
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          labels: Private Tests
