---
name: Test not-from-fork steps

on:
  push:
    branches:
      - main
      - fix-calls-test-testbranch
  pull_request:

jobs:
  test-fork:
    runs-on: ubuntu-22.04
    steps:
      - name: test-fork/test
        env:
          GITHUB_HEAD_REPO_FORK: "${{ github.event.pull_request.head.repo.fork }}"
          GITHUB_EVENT_REPO_FULLNAME: "${{ github.event.repository.full_name }}"
          GITHUB_REPO: "${{ github.repository }}"
        run: |
          for VAR in GITHUB_HEAD_REPO_FORK GITHUB_EVENT_REPO_FULLNAME GITHUB_REPO; do
            echo "$VAR=${!VAR}"
          done
      - name: Not on a fork
        if: "! github.event.pull_request.head.repo.fork"
        run: echo "Not on a fork"
